#' @title Compute HiCPotts Probabilities of Assigning an Interaction to Each Component
#'
#' @description
#' This function computes the posterior probabilities of assigning genomic interactions to each of three mixture components (or states) in a Hidden Markov Random Field (HMRF) model.
#' It uses the posterior means of regression parameters obtained from MCMC simulations and combines these with user-specified distributions (zero-inflated or standard)
#' to produce probabilities for each observed interaction.
#'
#' @usage
#' compute_HMRFHiC_probabilities(data, chain_betas, 
#'    iterations, dist = "ZINB", max_interactions = NA_integer_, 
#'      consistent_dist = TRUE)
#'
#' @param data A \code{data.frame} containing the following required columns:
#'   \itemize{
#'     \item \code{start}: Genomic start position for locus i.
#'     \item \code{end}: Genomic end position for locus j.
#'     \item \code{interactions}: Observed interaction counts between loci i and j.
#'     \item \code{GC}: GC content or related genomic feature for the interaction.
#'     \item \code{TES}: Transposable Elements data or similar regulatory measure.
#'     \item \code{ACC}: Accessibility measure or another continuous genomic covariate.
#'   }
#'   The \code{start} and \code{end} columns must correspond to the indices of interacting loci (i and j).
#'
#' @param chain_betas A list of MCMC chain results generated by the HiCPotts model-fitting procedure. Each element should correspond to one chain and must include:
#'   \itemize{
#'     \item \code{chains}: A list of 3 MCMC chains (one for each component), each containing posterior samples of regression coefficients.
#'     \item \code{theta}: (If applicable) Posterior samples of the zero-inflation parameter \eqn{\theta}.
#'     \item \code{size}: (If applicable) Posterior samples for the overdispersion parameter used in Negative Binomial or Zero-Inflated Negative Binomial models.
#'   }
#'
#' @param iterations An integer specifying the number of total MCMC iterations. The function uses half of these as burn-in (i.e., \code{iterations/2}).
#'
#' @param dist A character string indicating the chosen distribution for modeling interaction counts. One of:
#'   \itemize{
#'     \item \code{"ZIP"}: Zero-Inflated Poisson
#'     \item \code{"NB"}: Negative Binomial
#'     \item \code{"Poisson"}: Poisson
#'     \item \code{"ZINB"}: Zero-Inflated Negative Binomial
#'   }
#'   The default is \code{"ZINB"}.
#'
#' @param max_interactions Optional cap on interactions before density eval. Defaults to NA.
#' @param consistent_dist  Logical; if TRUE, all three components use the same distribution.
#'
#' @details
#' This function is part of the HiCPotts pipeline that models genomic interactions (e.g., Hi-C interaction counts) using a mixture model approach.
#' The model typically considers three components (or latent states), each characterized by a distinct mean-structure and potentially different
#' zero-inflation or overdispersion parameters, depending on the chosen distribution.
#'
#' The function:
#' \enumerate{
#'   \item Extracts posterior means of regression parameters from MCMC chains, discarding the initial half of the samples as burn-in.
#'   \item Estimates mean interaction intensities (\eqn{\lambda}) for each component using log-linear models with covariates: distance (log of |end-start|),GC, TES, and ACC (each transformed by a log(\eqn{x+1}) operation).
#'   \item Given the specified distribution (\code{dist}), calculates the probability (on the natural scale) of observing the recorded interaction count for each component.
#'   \item Normalizes these probabilities so that each interaction is assigned a set of three probabilities summing to 1.
#' }
#'
#' For zero-inflated distributions (\code{"ZIP"}, \code{"ZINB"}), a \eqn{\theta} parameter captures the probability of an excess zero.
#' For negative binomial distributions (\code{"NB"}, \code{"ZINB"}), an overdispersion parameter is included.
#'
#' The computed probabilities can be used for downstream analysis, such as segmenting interactions into classes or modeling spatial dependence in a hidden Markov field.
#'
#' @return
#' A \code{data.frame} containing the original input columns plus three new columns:
#' \itemize{
#'   \item \code{prob1}: The posterior probability that the interaction belongs to component 1.
#'   \item \code{prob2}: The posterior probability that the interaction belongs to component 2.
#'   \item \code{prob3}: The posterior probability that the interaction belongs to component 3.
#' }
#'
#' The returned data frame thus provides a probabilistic classification of each observed interaction into one of the three modeled components.
#'
#' @examples
#' #
#' #
#' # Synthetic data
#' set.seed(123)
#' 
#' 
#' large_data <- data.frame(
#'   start = c(1, 10, 20),
#'   end = c(5, 15, 30),
#'   interactions = c(10, 20, 30),
#'   GC = c(0.5, 0.8, 0.3),
#'   TES = c(0.2, 0.5, 0.7),
#'   ACC = c(0.9, 0.4, 0.6)
#' )
#'
#' chain_betas <- list(
#'   list(
#'     chains = list(
#'       matrix(runif(30, 0.1, 1), ncol = 5),
#'       matrix(runif(30, 0.1, 1), ncol = 5),
#'       matrix(runif(30, 0.1, 1), ncol = 5)
#'     ),
#'     theta = runif(6, 0.1, 0.9),
#'     size = matrix(runif(18, 1, 10), nrow = 3)
#'   )
#' )
#'
#' result <- compute_HMRFHiC_probabilities(
#'   data = large_data,
#'   chain_betas = chain_betas,
#'   iterations = 5,
#'   dist = "Poisson", max_interactions = NA_integer_, consistent_dist = TRUE
#' )
#' print(result)
#' # See vignette("HiCPotts_vignette") for detailed examples with real Hi-C data.
#' #
#' #
#'
#' @seealso
#' \code{\link{dpois}}, \code{\link{dnbinom}}, for probability calculations.
#'
#' @export
#'
compute_HMRFHiC_probabilities <- function(data, chain_betas, iterations, dist = "ZINB", max_interactions = NA_integer_, consistent_dist  = TRUE) {
  # Check for required columns in data
  .check_required_columns(data)

  dist <- match.arg(dist, c("Poisson", "NB", "ZIP", "ZINB"))
  
  # Prepare mydata data frame
  mydata <- data.frame(start = data$start, end = data$end, interactions = data$interactions, GC = data$GC, TES = data$TES, ACC = data$ACC, stringsAsFactors = FALSE)
  
  interactions <- mydata$interactions
  distance <- log1p(abs(mydata$end - mydata$start))
  GC <- log1p(mydata$GC)
  TES <- log1p(mydata$TES)
  ACC <- log1p(mydata$ACC)

  ## proper integer burn-in that keeps the last sample and never produces fractional indices.
  if (!is.numeric(iterations) || length(iterations) != 1L || iterations < 2) {
    stop("iterations must be a positive scalar of at least 2.")
  }
  burnin    <- floor(iterations / 2L)
  idx_range <- (burnin + 1L):(iterations + 1L)          # include last sample
  
  ## posterior means per chain, per component, per coefficient 
  extract_mean <- function(chain_list, col) {
    vapply(chain_list, function(chain) {
      vapply(seq_len(3L), function(j)
        mean(chain[["chains"]][[j]][idx_range, col]), numeric(1))
    }, numeric(3))
  }
  
  # Each of these is a 3 x n_chains matrix
  intercept_mat <- extract_mean(chain_betas, 1L)
  distance_mat  <- extract_mean(chain_betas, 2L)
  GC_mat        <- extract_mean(chain_betas, 3L)
  TES_mat       <- extract_mean(chain_betas, 4L)
  ACC_mat       <- extract_mean(chain_betas, 5L)
  
  comp_mean <- function(mat, comp) mean(mat[comp, ])   # average over chains
  
  intercept <- vapply(1:3, function(c) comp_mean(intercept_mat, c), numeric(1))
  distance_b<- vapply(1:3, function(c) comp_mean(distance_mat,  c), numeric(1))
  GC_b      <- vapply(1:3, function(c) comp_mean(GC_mat,        c), numeric(1))
  TES_b     <- vapply(1:3, function(c) comp_mean(TES_mat,       c), numeric(1))
  ACC_b     <- vapply(1:3, function(c) comp_mean(ACC_mat,       c), numeric(1))
  
  theta <- if (dist %in% c("ZIP", "ZINB")) {
    mean(vapply(chain_betas, function(ch) mean(ch[["theta"]][idx_range]),
                numeric(1)))
  } else NULL
  
  overdisp <- if (dist %in% c("NB", "ZINB")) {
    vapply(1:3, function(c)
      mean(vapply(chain_betas,
                  function(ch) mean(ch[["size"]][c, idx_range]),
                  numeric(1))),
      numeric(1))
  } else rep(NA_real_, 3)
  
  ##linear predictors per component 
  eta <- function(c)
    intercept[c] + distance_b[c]*distance + GC_b[c]*GC + TES_b[c]*TES + ACC_b[c]*ACC
  
  lambda_1 <- exp(eta(1L))
  lambda_2 <- exp(eta(2L))
  lambda_3 <- exp(eta(3L))
  
  ##optional truncation of y
  interactions_eval <- if (is.na(max_interactions)) interactions
  else pmin(interactions, as.integer(max_interactions))
  
  ##log-density under distribution dist
  log_density <- function(y, lambda, theta, overdisp, use_dist) {
    switch(use_dist,
           "Poisson" = dpois(y, lambda = lambda, log = TRUE),
           "NB"      = dnbinom(y, size = overdisp, mu = lambda, log = TRUE),
           "ZIP"     = ifelse(y == 0,
                              log(theta + (1 - theta) * exp(-lambda)),
                              log1p(-theta) + dpois(y, lambda = lambda, log = TRUE)),
           "ZINB"    = ifelse(y == 0,
                              log(theta + (1 - theta) *
                                    dnbinom(0, size = overdisp, mu = lambda)),
                              log1p(-theta) + dnbinom(y, size = overdisp, mu = lambda,
                                                      log = TRUE)),
           stop("Invalid distribution specified.")
    )
  }
  
  ## distribution for components 2 and 3:
  ##  consistent_dist = TRUE  -> same as dist (new, default)
  ##  consistent_dist = FALSE -> Poisson (for ZIP/Poisson) or NB (for NB/ZINB)
  dist_23 <- if (consistent_dist) dist
  else if (dist %in% c("Poisson", "ZIP")) "Poisson" else "NB"
  
  lp1 <- log_density(interactions_eval, lambda_1, theta, overdisp[1], dist)
  lp2 <- log_density(interactions_eval, lambda_2, theta, overdisp[2], dist_23)
  lp3 <- log_density(interactions_eval, lambda_3, theta, overdisp[3], dist_23)
  
  ## normalise via log-sum-exp to avoid underflow
  m     <- pmax(lp1, pmax(lp2, lp3))
  e1    <- exp(lp1 - m); e2 <- exp(lp2 - m); e3 <- exp(lp3 - m)
  denom <- e1 + e2 + e3
  
  mydata$prob1 <- as.vector(e1 / denom)
  mydata$prob2 <- as.vector(e2 / denom)
  mydata$prob3 <- as.vector(e3 / denom)
  
  mydata
}
