# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_metropolis_MCMC_betas <- function(N, gamma_prior, iterations, x_vars, y, use_data_priors, user_fixed_priors = NULL, dist = "ZIP", epsilon = NULL, distance_metric = "manhattan", size_start = NULL, theta_start = NULL) {
    .Call('_HMRFHiC_run_metropolis_MCMC_betas', PACKAGE = 'HMRFHiC', N, gamma_prior, iterations, x_vars, y, use_data_priors, user_fixed_priors, dist, epsilon, distance_metric, size_start, theta_start)
}

Neighbours_combined <- function(potts_data, N, proposed_value = NULL) {
    .Call('_HMRFHiC_Neighbours_combined', PACKAGE = 'HMRFHiC', potts_data, N, proposed_value)
}

pz_123 <- function(z, sum_neighbours, y, pred_combined, chains, chain_gamma, x_vars, theta, size_chain, N, iter, dist) {
    .Call('_HMRFHiC_pz_123', PACKAGE = 'HMRFHiC', z, sum_neighbours, y, pred_combined, chains, chain_gamma, x_vars, theta, size_chain, N, iter, dist)
}

